### ISSUE TITLE
Unable to execute tis script when passing long length of string in HOST name in json file

### ISSUE THREAD

**Issue by sachinmkp1** [datawrangl3r/mongoes#1]
When I am trying to run the main script of this program getting below error:

R:\mongoes-master>python __init__.py

ConnectionError(Failed to parse: 'https://search-ahsw-nit-rfbqqq3bkl4cgg2jxivsg2q.us-2.es.amazonaws.com/_plugin/kibana', label empty or too long) caused by: Locat
ionParseError(Failed to parse: 'https://search-ahsw-nit-rfbqqq3bkl4cgg2jxivsg2q.us-2.es.amazonaws.com/_plugin/kibana', label empty or too long)

This https is from aws elasticsearch that is endpoint.
------------------------------------------------------------------
In json configuration file:
{
	"EXTRACTION":
		{
			"HOST": "https://search-ahsw-nit-rfbqqq3bkl4cgg2jxivsg2q.us-2.es.amazonaws.com/_plugin/kibana",
			"INDEX": "abcELKINDEX",
			"DBENGINE": "elasticsearch"
		},
	"COMMIT":
		{
			"HOST": "localhost",
			"DATABASE": "test",
			"COLLECTION": "test",
			"DBENGINE": "mongo",
			"PORT":27017
		}
}

Note this Host value is dummy  just consider it long kind of string.

What is wrong in this.

Thanks,

**Comment by datawrangl3r** [comment]
Thanks for raising the issue, @sachinmkp1 
It's not the issue about the length of the string but the label.
Can you try using: `https://search-ahsw-nit-rfbqqq3bkl4cgg2jxivsg2q.us-2.es.amazonaws.com` as the HOST value?
